[package]
name = "vulkan-rs"
version = "0.1.0"
authors = ["hodasemi <superschneider@t-online.de>"]
edition = "2018"

[dependencies]
shared_library = "0.1.9"
image = "0.22.3"
utilities = { path = "../utilities" }
vulkan-sys = { path = "../vulkan-sys" }
