[package]
name = "utilities"
version = "0.1.0"
authors = ["hodasemi <michaelh.95@t-online.de>"]
edition = "2018"

[dependencies]
cgmath = { version = "0.17.0", features = ["swizzle"] }
rand = "0.7.2"
failure = "0.1.6"